image: streampusher/streampusher:latest
services:
  - postgres
  - redis

variables:
  CI: "true"
  S3_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  S3_SECRET: "xxxxxxxxxxxxxxxxxxxxx"
  ADMIN_EMAIL: "info@datafruits.fm"
  STRIPE_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  STRIPE_PUBLIC_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  MIXCLOUD_TOKEN: "xxxxxxxxxxxxxxxxx"

job1:
  cache:
    paths:
      - "frontend/node_modules"
      - "vendor/bundle"
  script: "script/ci.sh"
