image: streampusher/streampusher
services:
  - postgres
  - redis

variables:
  CI: "true"
  S3_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  S3_SECRET: "xxxxxxxxxxxxxxxxxxxxx"
  ADMIN_EMAIL: "info@datafruits.fm"
  STRIPE_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  STRIPE_PUBLIC_KEY: "xxxxxxxxxxxxxxxxxxxxx"
  MIXCLOUD_TOKEN: "xxxxxxxxxxxxxxxxx"

before_script:
  - eval "$(rbenv init -)"
  - echo $PATH
  - gem install bundler
  - cp config/database.ci.yml config/database.yml
  - bundle install --jobs $(nproc)
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake ember:install

job1:
  cache:
    paths:
      - "frontend/node_modules"
      - "vendor/bundle"
  script: "rake spec"
