image: streampusher/streampusher
services:
  - postgres
  - redis

before_script:
  - cp config/database.example.yml config/database.yml
  - bundle install --jobs $(nproc)
  - bundle exec rake db:create
  - bundle exec rake db:migrate

job1:
  script: "rake spec"
