image: ruby:2.1
services:
  - postgres
  - redis

before_script:
  - "apt-get install -y build-essential libtag1-dev"
  - bundle install --jobs $(nproc)
  - bundle exec rake db:create
  - bundle exec rake db:migrate

job1:
  script: "rake spec"
