version: '2'
services:
  listenerproxy:
    image: "mcfiredrill/listener_proxy:latest"
    ports:
     - "8000:8000"
    restart: "always"
  redis:
    image: "redis:3.2.1"
    ports:
      - "6379:6379"
    restart: "always"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
