version: '2'
services:
  listenerproxy:
    image: "mcfiredrill/listener_proxy:latest"
    ports:
     - "8000:8000"
    restart: "always"
  redis:
    image: "dockerfile/redis:latest"
    ports:
      - "6379:6379"
    restart: "always"
    command: "redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}"
