development:
  APP_HOSTNAME: 'streampusher.dev'
  S3_BUCKET: "streampusherdev"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

test:
  S3_BUCKET: "streampushertest"
