development:
  adapter: postgresql
  database: stream_pusher_dev
  pool: 5
  timeout: 5000
  username: stream_pusher
  password: password

production:
  adapter: postgresql
  database: stream_pusher_production
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: stream_pusher_test
  pool: 5
  timeout: 5000
